### ISSUE TITLE
Empty RSS feed

### ISSUE THREAD

**Issue by kogakure** [joshmedeski/joshmedeski.com#2]
I found your blog and the cool productivity tips and would like to follow it via RSS, but [the feed is empty](https://www.joshmedeski.com/rss.xml). The reason is probably™ that your folder is not called `blog`, but `posts`.

It would help additionally to make the RSS feed known to RSS aggregators, by adding something like this to the `<head>`:

```html
<link rel="alternate" type="application/rss+xml" title="Josh Medeski" href="https://www.joshmedeski.com/rss.xml">
```

https://github.com/joshmedeski/joshmedeski.com/blob/c7ed42872a5115c144b4ecbd79fdd52d6b809d26/src/pages/rss.xml.js#L9

**Comment by joshmedeski** [comment]
Thanks for the heads up, I fixed it with https://github.com/joshmedeski/joshmedeski.com/commit/119acbeae108b3c13fbe8f5418b1d463ec66f953 and it's been tested and published.
